%% get_nav_logic_script_text.
% Returns the text for the script inside the Navigation_Logic block.

function script = get_nav_logic_script_text()
%GET_NAV_LOGIC_SCRIPT_TEXT Returns the MATLAB code for the Navigation_Logic block.
%   This function outputs a complete, newline-separated string containing the
%   definition of the Navigation_Logic MATLAB Function block, matching the ICD:
%     - Inputs: latitude, longitude, altitude
%     - Outputs: nav (NavigationBus struct with fields in ICD order)
    script = [ ...
        'function NavBus = fcn(PosBus)\n' ...
        ' %#codegen\n' ...
        ' \n' ...
        ' % Initialize the output bus to a known, safe state\n' ...
        ' NavBus = initialize_navigation_bus();\n' ...
        ' \n' ...
        ' % Call Python bridge to get the active flight leg\n' ...
        ' try\n' ...
        '     leg_data = py.interfaces.matlab_python_bridge.get_current_leg_bridge();\n' ...
        ' catch\n' ...
        '     % If Python isn''t running, default to an empty set to prevent errors\n' ...
        '     leg_data = []; \n' ...
        ' end\n' ...
        ' \n' ...
        ' % Only perform calculations if a valid flight leg exists\n' ...
        ' if ~isempty(leg_data)\n' ...
        '     start_wp = leg_data.start_waypoint;\n' ...
        '     end_wp = leg_data.end_waypoint;\n' ...
        '     \n' ...
        '     % Call EXTERNAL .m files for calculations (enhances maintainability)\n' ...
        '     [dist_nm, bearing_deg] = calculate_distance_bearing(PosBus.latitude, PosBus.longitude, end_wp.latitude, end_wp.longitude);\n' ...
        '     xte_nm = calculate_cross_track_error(PosBus.latitude, PosBus.longitude, start_wp.latitude, start_wp.longitude, end_wp.latitude, end_wp.longitude);\n' ...
        '     \n' ...
        '     % Bank angle command calculation per SDD guidance\n' ...
        '     bank_angle_cmd_deg = calculate_bank_angle_cmd(xte_nm, bearing_deg);\n' ...
        '     \n' ...
        '     % Populate the output bus struct\n' ...
        '     NavBus.CrossTrackError_nm = xte_nm;\n' ...
        '     NavBus.DistanceToGo_nm = dist_nm;\n' ...
        '     NavBus.DesiredCourse_deg = bearing_deg;\n' ...
        '     NavBus.BankAngleCmd = bank_angle_cmd_deg;\n' ...
        ' end\n' ...
        'end\n' ...
        '\n' ...
        'function bus = initialize_navigation_bus()\n' ...
        '  % Creates a zero-filled struct matching the NavigationBus definition\n' ...
        '  % This prevents errors when no flight plan is active.\n' ...
        '  bus = struct;\n' ...
        '  bus.CrossTrackError_nm = 0;\n' ...
        '  bus.DistanceToGo_nm = 0;\n' ...
        '  bus.DesiredCourse_deg = 0;\n' ...
        '  bus.BankAngleCmd = 0;\n' ...
        'end' ...
    ];
end


