%% get_nav_logic_script_text.
% Returns the text for the script inside the Navigation_Logic block.

function script = get_nav_logic_script_text()
%GET_NAV_LOGIC_SCRIPT_TEXT Returns the MATLAB code for the Navigation_Logic block.
%   This function outputs a complete, newline-separated string containing the
%   definition of the Navigation_Logic MATLAB Function block, matching the ICD:
%     - Inputs: latitude, longitude, altitude
%     - Outputs: nav (NavigationBus struct with fields in ICD order)

script = sprintf([
    'function nav = Navigation_Logic(latitude, longitude, altitude)\n' ...
    '%#codegen\n' ...
    '% Initialize output bus struct per ICD (cross track error, distance, course, bank angle)\n' ...
    'nav = struct(''CrossTrackError'',0, ''DistanceToGo'',0, ''DesiredCourse'',0, ''BankAngleCmd'',0);\n' ...
    '\n' ...
    '% --- Placeholder computations (replace with real implementations) ---\n' ...
    '% Compute distance and bearing to next waypoint\n' ...
    '[dist_nm, bearing_deg] = computeDistanceAndBearing(latitude, longitude);\n' ...
    '% Compute cross-track error relative to desired track\n' ...
    'xte_nm = computeCrossTrackError(latitude, longitude);\n' ...
    '\n' ...
    '% Assign computed values to bus fields\n' ...
    'nav.CrossTrackError = xte_nm;\n' ...
    'nav.DistanceToGo    = dist_nm;\n' ...
    'nav.DesiredCourse   = bearing_deg;\n' ...
    '% Compute commanded bank angle (placeholder)\n' ...
    'nav.BankAngleCmd    = computeBankAngle(xte_nm, dist_nm, bearing_deg);\n' ...
    '\n' ...
    'end\n' ...
]);

end
